### ISSUE TITLE
WTA match data : commit_a8c11eb_thru_26_nov_2018 : 'Makarova bug' has resurfaced 

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_wta#14]
Hi,

I really appreciate the work done in the 'commit_a8c11eb_thru_26_nov_2018' update.

Unfortunately, [I hate to be the bearer of bad news] the 'Makarova bug' has resurfaced, with Ekaterina Makarova (ranking ~ 50, wta id 201505) looking like she's been playing a slew of $15k tourneys under the radar over the last couple of months. I'm quessing instead it was Ekaterina Makarova 1996 (wta id 221247).

Hope this helps,
bazzaar

**Comment by mkleinercz** [comment]
Hi,
wta_matches_2020.csv in the commit '05db815' has mismatch in columns.
In column 'winner_rank' are data 'loser_id'.
Best regards
Martin

**Comment by JeffSackmann** [comment]
merging this to #17, also re: makarovas
