### ISSUE TITLE
WTA players : Advanced age at end of [rankings] career may indicate data issue.

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_wta#16]
Hi,
Some players have an advanced age at the end of their spell in the rankings, and while this may be accurate in many cases, it may indicate issues with dob, or even players sharing the same WTA id.

| id |    fname    |     lname     | hand |    dob     | country | rank_begin |  rank_end  | rankdays |     age_rank_begin       |      age_rank_end        |
|--------|-------------|---------------|------|------------|---------|------------|------------|----------|--------------------------|--------------------------|
| 201125 | Elizabeth   | James         | U    | 1946-05-15 | GBR     | 2012-04-09 | 2017-01-23 |     1750 | 65 years 10 mons 25 days | 70 years 8 mons 8 days   |
| 200376 | Katerina    | Bohmova       | L    | 1958-01-22 | CZE     | 1987-01-05 | 2012-06-04 |     9282 | 28 years 11 mons 14 days | 54 years 4 mons 13 days  |
| 201090 | Stephanie   | Johnson       | U    | 1946-03-08 | USA     | 1995-10-02 | 1999-10-18 |     1477 | 49 years 6 mons 25 days  | 53 years 7 mons 10 days  |

These are the three players who [currently in this repo] are shown as the oldest when they finally dropped from the rankings list. It appears that in each case, the id assigned to these players is also assigned to the data for another un-named younger player, thereby erroneously extending the ranking careers and match records data for all these players.

### **id 201125**
 - assigned to Elizabeth 'Liz' James (GBR - Wales) dob 1946-05-15

These are the counts of the player's appearance in the ranking lists per year

|   fname   |   lname   | hand |    dob     | country | id_org | year | count |
|-----------|-----------|------|------------|---------|--------|------|-------|
| Elizabeth | James     | U    | 1946-05-15 | GBR     | 201125 | 2012 |    35 |
| Elizabeth | James     | U    | 1946-05-15 | GBR     | 201125 | 2013 |    11 |
| Elizabeth | James     | U    | 1946-05-15 | GBR     | 201125 | 2015 |     2 |
| Elizabeth | James     | U    | 1946-05-15 | GBR     | 201125 | 2016 |    50 |
| Elizabeth | James     | U    | 1946-05-15 | GBR     | 201125 | 2017 |     4 |

I've verified that all these ranking records belong instead to: 

| id | name | nat | dob| hand |
|-----|---------------------|-----|-------------|-----|
|  ? | Elizabeth James 1994 | AUS | 1994-04-27 | R |

Therefore the action required is to set up a new player record for this younger player, and move the rankings data over to her id.

In addition, there's some match data to reassign to the new id.

|  id    |      name        | tourney_date | win  | lose | nat | action    |
|--------|------------------|--------------|------|------|-----|-----------|
| 201125 | Elizabeth James  |  2017-09-18  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2016-01-25  |    1 |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2016-01-18  |    1 |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2016-01-11  |    1 |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2015-12-07  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2015-11-23  |    2 |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2012-10-29  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2012-10-22  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2012-03-26  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2011-10-10  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  2011-10-03  |      |    1 | AUS | change id |
| 201125 | Elizabeth James  |  1971-06-21  |      |    1 | GBR | id ok     |
| 201125 | Elizabeth James  |  1970-06-22  |      |    1 | GBR | id ok     |
| 201125 | Elizabeth James  |  1969-06-23  |      |    1 | GBR | id ok     |

### **id 201090**
 - assigned to Stephanie Johnson (USA) dob 1946-03-08 U-hand

Firstly, the name of this player is incorrect, she played under her maiden name, and she played left-handed, so her player record should be amended like so : 

| id | name | nat | dob| hand |
|-----|---------------------|-----|-------------|-----|
|  201090 | Stefanie DeFina  | USA | 1946-03-08 | L |

The player assumed the name Stephanie DeFina-Johnson after she retired from top level tennis.

These are the counts of the player's appearance in the ranking lists per year

|   fname   |   lname   | hand |    dob     | country | id_org | year | count |
|-----------|-----------|------|------------|---------|--------|------|-------|
| Stephanie | Johnson    | U    | 1946-03-08 | USA | 201090 | 1995 |    13 |
| Stephanie | Johnson    | U    | 1946-03-08 | USA | 201090 | 1996 |    53 |
| Stephanie | Johnson    | U    | 1946-03-08 | USA | 201090 | 1997 |    52 |
| Stephanie | Johnson    | U    | 1946-03-08 | USA | 201090 | 1998 |    53 |
| Stephanie | Johnson    | U    | 1946-03-08 | USA | 201090 | 1999 |    33 |

I've verified, however, that all these ranking records belong instead to: 

| id | name | nat | dob| hand |
|-----|---------------------|-----|-------------|-----|
|  ? | Stephanie Johnson 1971 | USA | 1971-12-07 | U |

Therefore the action required is to set up a new player record for this younger player, and move the rankings data over to her id.

By the way, there is **another**, even younger, as yet unranked, USA player named Stephanie Johnson on the WTA site, so the potential is there for quite a data muddle to occur. I suggest another player record should be added (because one of the existing match records belongs to her), like so :
 
| id | name | nat | dob| hand |
|-----|---------------------|-----|-------------|-----|
|  ? | Stephanie Johnson 1998 | USA | 1998-03-20 | R |

In addition, there's some match data to reassign to the two new id's (of Stephanie Johnson 1971, and Stephanie Johnson 1998).

|  id    |    name                    | tourney_date | win  | lose | comment                                                             |
|--------|---------------------------|---------------|------|------|--------------------------------------------------------------|
| 201090 | Stephanie Johnson |  2015-07-27  |      |    1 | change id to that of Stephanie Johnson 1998   |
| ------ |        14 year    |   gap        |      |      |                                               |
| 201090 | Stephanie Johnson |  2001-07-16  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1999-08-02  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1998-05-04  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1997-10-01  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1997-07-07  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-10-14  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-10-07  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-06-24  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-03-19  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-03-11  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-03-04  |      |    1 | change id to that of Stephanie Johnson 1971   |
| 201090 | Stephanie Johnson |  1996-02-26  |      |    1 | change id to that of Stephanie Johnson 1971   |
| ------ |        15 year    |   gap        |      |      |                                               |
| 201090 | Stephanie Johnson |  1971-09-01  |      |    1 | amend (Stefanie DeFina, R-hand) match records |
| 201090 | Stephanie Johnson |  1970-09-02  |    1 |    1 | amend (Stefanie DeFina, R-hand) match records |
| 201090 | Stephanie Johnson |  1970-06-22  |      |    1 | amend (Stefanie DeFina, R-hand) match records |
| 201090 | Stephanie Johnson |  1968-08-29  |      |    1 | amend (Stefanie DeFina, R-hand) match records |
| 201090 | Stephanie Johnson |  1968-06-24  |    1 |    1 | amend (Stefanie DeFina, R-hand) match records |

### **id 200376**
 - assigned to Katerina Bohmova (CZE) dob 1958-01-22 L-hand

These are the counts of the player's appearance in the ranking lists per year

|   fname   |   lname   | hand |    dob     | country | id | year | count |  comment  |
|-----------|-----------|------|-------------|---------|--------|------|-------|-----------|
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 1987 |    22 | mother    |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 1988 |    39 | mother    |
| --------  | --------  | ----- | 14 year |   gap     |        |      |       |           |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2002 |    10 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2003 |    52 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2004 |    51 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2005 |    53 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2006 |    53 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2007 |    53 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2008 |    14 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2010 |    24 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2011 |    53 | daughter  |
| Katerina  | Bohmova   | L    | 1958-01-22 | CZE     | 200376 | 2012 |    24 | daughter  |

I've verified that the pre-2000 ranking records are correctly assigned to Katerina Bohmova (now. Bohmova-Skronska), however all the post-2000 ranking records belong instead to her daughter, with the same name: 

| id | name | nat | dob| hand |
|-----|---------------------|-----|-------------|-----|
|  ? | Katerina Bohmova 1986 | CZE | 1986-11-18 | L |

Therefore the action required is to set up a new player record for this younger player, and move the post-2000 rankings data over to her id.

In addition, there's some match data to reassign to the new id.

|  id    |       name       | tourney_date | win  | lose | action    |
|--------|------------------|--------------|------|------|-----------|
| 200376 | Katerina Bohmova | 2011-06-06   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2011-05-30   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2010-11-22   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2010-11-15   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2010-07-12   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2010-06-07   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2010-05-31   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2008-02-04   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-10-08   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-03-26   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-03-12   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-02-26   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2007-02-19   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-02-12   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2007-01-29   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-01-22   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-01-15   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2007-01-01   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-11-13   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-10-30   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-10-16   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-10-02   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-09-25   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-09-18   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-09-04   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-08-14   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-08-07   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-07-31   |    4 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-07-24   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-07-17   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-07-03   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-06-26   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-06-12   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-06-05   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-05-15   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-05-08   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-05-01   |    4 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-04-10   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-04-03   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-03-20   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-03-13   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-03-06   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-02-27   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-02-20   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-02-06   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-01-30   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-01-16   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2006-01-09   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2006-01-02   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-11-28   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-11-14   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-10-24   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-10-03   |    5 |      | change id |
| 200376 | Katerina Bohmova | 2005-09-26   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-09-19   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-09-05   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-08-29   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-08-15   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-07-25   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-07-18   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-07-11   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-06-27   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-06-20   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-06-06   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-05-30   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-05-23   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-05-09   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-05-02   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-04-25   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-04-18   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-04-04   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-03-23   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-03-09   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-02-21   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-02-14   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-02-07   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-01-31   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-01-24   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2005-01-17   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2005-01-10   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2004-12-13   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-11-22   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-10-04   |    3 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-09-27   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2004-09-06   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-08-30   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2004-08-02   |    4 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-07-12   |    2 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-06-14   |    5 |      | change id |
| 200376 | Katerina Bohmova | 2004-06-07   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-05-17   |    4 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-04-26   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-04-12   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-03-22   |    4 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-02-09   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2004-01-26   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2003-10-27   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2003-09-29   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2003-09-15   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2003-08-18   |    5 |      | change id |
| 200376 | Katerina Bohmova | 2003-07-28   |    1 |    1 | change id |
| 200376 | Katerina Bohmova | 2003-07-14   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2003-02-24   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2002-10-21   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2002-09-23   |      |    1 | change id |
| 200376 | Katerina Bohmova | 2002-07-22   |    1 |    1 | change id |
| ------ |        15 year   |  gap         |      |      |           |
| 200376 | Katerina Bohmova | 1987-09-21   |    1 |    1 | id ok     |
| ------ | all dates in | between          | ---- | ---- | id ok     |
| 200376 | Katerina Bohmova | 1978-05-15   |    1 |    1 | id ok     |

Hope this helps,
bazzaar

**Comment by JeffSackmann** [comment]
thanks for the detailed report. fixed.

**Comment by bazzaar** [comment]
Glad to be of help. I've been busy on other projects for a year or so, but I hope to get back the tennis data before too long. Thanks again for the work you do, Jeff.
