### ISSUE TITLE
Na Li playing in 2016

### ISSUE THREAD

**Issue by AndreRoehrig** [JeffSackmann/tennis_wta#20]
The following match seems to be a different Na Li from the one the data indicates, as she already was retired and the official ITF site gives another age for the actual Na Li playing here:

`2016-W-C25-CHN-01A-2016,Naiman $25K,Hard,32,25,20160808,3,215045,,Q,Xinyu Jiang,U,,CHN,17.4346338125,201419,,WC,Na Li,R,172,CHN,34.4476386037,6-2 6-4,3,R32,,,,,,,,,,,,,,,,,,,,869,14,,`

**Comment by Detsnoos** [comment]
You right, it's not the same Na Li.
I found the game here : [https://www.tennisexplorer.com/player/jiang-90cf1/?annual=2016](url)

**Player info :** 
Li Na (1994)
Country: China
Age: 26 (27. 1. 1994)
Sex: woman
Plays: right

**Comment by JeffSackmann** [comment]
fixed. thanks to both.
