### ISSUE TITLE
Tennis Abstract Player_ids are not unique...

### ISSUE THREAD

**Issue by TennisVisuals** [JeffSackmann/tennis_wta#6]
tennis_atp begins with 100001,Gardnar,Mulloy,R,19131122,USA 
but the numbers go beyond 200000

tennis_atp begins with 200000,X,X,U,19000000,UNK

so that ATP: 200033,Kushaan,Nath,R,19971117,IND 
has the same player_id as WTA: 200033,Serena,Williams,R,19810926,USA

it would be nice if a tennis abstract id were truly unique...

**Comment by JeffSackmann** [comment]
it would be nice, but alas, they are not.
