### ISSUE TITLE
network version of your data

### ISSUE THREAD

**Issue by SNAnalyst** [JeffSackmann/tennis_wta#70]
Hi Jeff,

Thank you for your work. I came across your repo a week ago and used some of it to show my students (in an introductory course on social network analysis for data scientists) on how to create network data from a real world repo and to show them how to manipulate and handle such objects. I found that a very useful exercise.

While I was at it, I figured it might be useful for others to have access to your data as a network structure. 
I have put up the datafiles on my repo here: https://github.com/SNAnalyst/tennisgRaphs

Please let me know if you are OK with this and whether the attribution and license use are OK. 

regards, Roger Leenders

**Comment by JeffSackmann** [comment]
Looks good, thanks for letting me know.
