### ISSUE TITLE
WTA rankings : 'ranking points' values have been erroneously truncated to integers 

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_wta#8]
Hi,

[UPDATE: from Issue#10 re.Whitlinger twins data, there is a suspicion that at least some of the 'Ranking Points' values are actually 'Average Points' data values]  

After comparing the official WTA year end ranking lists (available as pdf's from the WTA website) against the ranking data in this repo, it is clear that the data values in the 'Ranking Points' column in the wta_rankings_[70s|80s|90s|00s|10s].csv files in this repo have been erroneously truncated to integers.

This severely limits the usefulness of the Ranking Points data, especially for the pre-2008 rank lists, and even more especially for the lower end of the lists where many players had won just a few ( non-whole number ) points.

As a case in point, from the entire wta repo ranking dataset as it is currently set out, some 523 players never accumulated even a single wta ranking point throughout their career, their week-on-week efforts have been consistently truncated to zero points ... this in my view is badly wrong.

A specific example of this issue is in the official 1998 YE rankings list (23Nov1998), at the bottom of the list is player id:204173, Yuki Fujii, at 1074 rank position with 0.75 rank points, whereas in this repo she is attributed zero points.

I recommend that the rankings files be re-output, from whichever source they were derived, this time with the Ranking Points data values as floating point (4 decimal precision), rather than integer as is currently the case.

(I suspect this issue might also be the case for the mens atp rank data also, I'll investigate further, and if so, I'll open up a similar ticket there too).

I hope this helps.
bazzaar

**Comment by JeffSackmann** [comment]
i see your point. the source from which I drew the ranking and ranking points data (an older version of the WTA site) had already done the truncating. the latest version, as well as the version before that, of the WTA site have approximately no historical rankings data, so I don't think this is salvageable for week-by-week stats.
