### ISSUE TITLE
Contributing more WTA heights and handedness

### ISSUE THREAD

**Issue by andreakropp** [JeffSackmann/tennis_wta#83]
I'm contributing 408 additional player heights and 453 handedness additions or updates for the WTA_players.csv file. I wrote a program to loop through Wikipedia and examine the bio box that appears under the player photo. For height, if the height is in that box (in metric or English units) it is saved and converted to centimeters. For handedness the overwhelming majority of these row replace "U" for unknown. There are a few cases where I found "R" when the master file said "L" and vice versa. In those cases I visited the wikipedia page manually to confirm. If the wikipedia page is wrong, that's a different issue.
[hand_adds_wiki.csv](https://github.com/JeffSackmann/tennis_wta/files/7966407/hand_adds_wiki.csv)
[height_adds_wiki.csv](https://github.com/JeffSackmann/tennis_wta/files/7966408/height_adds_wiki.csv)

**Comment by JeffSackmann** [comment]
Thank you!
