### ISSUE TITLE
missing 2012 Olympics BR Azarenka-Kirilenko

### ISSUE THREAD

**Issue by JeffSackmann** [JeffSackmann/tennis_wta#97]

**Comment by MiaPumpkin** [comment]
If it helps, without stats it looks like this: (INPUT_DATA means it's up to you) 

2012-W-OL-GBR-01A-2012,Olympics,Grass,64,O,20120730,INPUT_DATA,201458,1,,Victoria Azarenka,R,180,BLR,22.9,201373,14,,Maria Kirilenko,R,173,RUS,25.5,6-3 6-4,3,INPUT_DATA,,,,,,,,,,,,,,,,,,,,1,8800,15,2615

based on your template:
tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
